### ISSUE TITLE
Replacement of input data

### ISSUE THREAD

**Issue by shushan2017** [bamtercelboo/pytorch_SRU#1]
Great project, I'm learning, but I haven't met my requirements for a long time. I just touched pytorch. I want to use imdb data for training. How do I do it? Thank you.

from keras.datasets import imdb
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)

**Comment by dalinvip** [comment]
keras? you are using keras framework,.

- The code can`t to support IMDB dataset, if you use it to train, you can download IMDB dataset to `data ` directory, and modify the python file in the `loaddata ` like  `loadingdata_Twitter.py`, and modify its relevant python file.

**Comment by shushan2017** [comment]
我的qq 3400219 可以请教您吗
